# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
  useradd -m -s /bin/bash -U iwase -u 666 --groups wheel
  chown -R iwase:iwase /home/iwase
  echo "%iwase ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/iwase
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.define "tomato" do |node|
    config.vm.box = "centos/7"
    config.vm.network "public_network", ip: "192.168.11.30"

    config.vm.provider "virtualbox" do |vb|
      #vb.customize ["modifyvm", :id, "--nictype1",  "virtio"]
      #vb.customize ["modifyvm", :id, "--nictype2",  "virtio"]
      vb.memory = "4096"
      vb.cpus = 3
    end

    config.disksize.size = '200GB'

    config.vm.provision "shell", inline: $script, privileged: true
  end

  config.vm.provision "shell", privileged: true, inline: <<-SCRIPT
    useradd -m -s /bin/bash -U iwase -u 666 --groups wheel
    mkdir -p /home/iwase/.ssh
    chown -R iwase:iwase /home/iwase
    echo "%iwase ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/iwase
  SCRIPT

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      mkdir -p /root/.ssh
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /home/iwase/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      chmod 0600 /home/vagrant/.ssh/authorized_keys
      chmod 0600 /home/iwase/.ssh/authorized_keys
      chmod 0600 /root/.ssh/authorized_keys
    SHELL
  end

end
