# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "benoki" do |node|
    config.vm.box = "centos/7"
    config.vm.network "public_network", ip: "192.168.50.3"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    config.vm.provision "shell", privileged: true, inline: <<-SHELL
      useradd -m -s /bin/bash -U iwase -u 666 --groups wheel
      mkdir -p /home/iwase/.ssh
      chown -R iwase:iwase /home/iwase
      echo "%iwase ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/iwase
    SHELL

    config.vm.provision "shell" do |s|
      ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
      s.inline = <<-SHELL
        mkdir -p /root/.ssh
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /home/iwase/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      SHELL
    end

    config.ssh.forward_agent = true

    config.vm.provision "shell", privileged: true, inline: <<-SHELL
      sudo yum install -y ansible
      sudo yum install -y git
    SHELL

    config.vm.provision "shell", privileged: true, inline: <<-SHELL
      git clone https://github.com/iwase22334/ansible-playbooks.git /home/iwase/ansible-playbooks
      chown -R iwase /home/iwase/ansible-playbooks
    SHELL

  end

end
